// Auto-generated by: supabase gen types typescript --local > types/database.ts
// Re-generate after any schema migration.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type UserRole = 'customer' | 'van_operator';
export type OrderStatus =
  | 'pending'
  | 'confirmed'
  | 'en_route'
  | 'ready'
  | 'collected'
  | 'rejected'
  | 'refunded';
export type SubscriptionTier = 'free' | 'pro';

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string;
          avatar_url: string | null;
          role: UserRole;
          expo_push_token: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          full_name: string;
          avatar_url?: string | null;
          role: UserRole;
          expo_push_token?: string | null;
          created_at?: string;
        };
        Update: {
          full_name?: string;
          avatar_url?: string | null;
          expo_push_token?: string | null;
        };
        Relationships: [];
      };
      van_operators: {
        Row: {
          id: string;
          profile_id: string;
          business_name: string;
          stripe_account_id: string | null;
          revenuecat_user_id: string | null;
          subscription_tier: SubscriptionTier;
          is_verified: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          business_name: string;
          stripe_account_id?: string | null;
          revenuecat_user_id?: string | null;
          subscription_tier?: SubscriptionTier;
          is_verified?: boolean;
          created_at?: string;
        };
        Update: {
          business_name?: string;
          stripe_account_id?: string | null;
          revenuecat_user_id?: string | null;
          subscription_tier?: SubscriptionTier;
          is_verified?: boolean;
        };
        Relationships: [];
      };
      vans: {
        Row: {
          id: string;
          operator_id: string;
          van_name: string;
          registration: string | null;
          jingle_url: string | null;
          is_available: boolean;
          current_lat: number | null;
          current_lng: number | null;
          last_ping: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          operator_id: string;
          van_name: string;
          registration?: string | null;
          jingle_url?: string | null;
          is_available?: boolean;
          current_lat?: number | null;
          current_lng?: number | null;
          last_ping?: string | null;
          created_at?: string;
        };
        Update: {
          van_name?: string;
          registration?: string | null;
          jingle_url?: string | null;
          is_available?: boolean;
          current_lat?: number | null;
          current_lng?: number | null;
          last_ping?: string | null;
        };
        Relationships: [];
      };
      menu_items: {
        Row: {
          id: string;
          van_id: string;
          name: string;
          description: string | null;
          price_gbp: number;
          image_url: string | null;
          is_available: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          van_id: string;
          name: string;
          description?: string | null;
          price_gbp: number;
          image_url?: string | null;
          is_available?: boolean;
          created_at?: string;
        };
        Update: {
          name?: string;
          description?: string | null;
          price_gbp?: number;
          image_url?: string | null;
          is_available?: boolean;
        };
        Relationships: [];
      };
      route_stops: {
        Row: {
          id: string;
          van_id: string;
          stop_order: number;
          street_name: string;
          postcode: string;
          lat: number;
          lng: number;
          eta: string;
          route_date: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          van_id: string;
          stop_order: number;
          street_name: string;
          postcode: string;
          lat: number;
          lng: number;
          eta: string;
          route_date?: string;
          created_at?: string;
        };
        Update: {
          stop_order?: number;
          street_name?: string;
          postcode?: string;
          lat?: number;
          lng?: number;
          eta?: string;
          route_date?: string;
        };
        Relationships: [];
      };
      orders: {
        Row: {
          id: string;
          customer_id: string;
          van_id: string;
          stop_id: string;
          status: OrderStatus;
          total_gbp: number;
          commission_gbp: number;
          stripe_payment_id: string | null;
          rejected_at: string | null;
          collected_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          van_id: string;
          stop_id: string;
          status?: OrderStatus;
          total_gbp: number;
          commission_gbp: number;
          stripe_payment_id?: string | null;
          rejected_at?: string | null;
          collected_at?: string | null;
          created_at?: string;
        };
        Update: {
          status?: OrderStatus;
          stripe_payment_id?: string | null;
          rejected_at?: string | null;
          collected_at?: string | null;
        };
        Relationships: [];
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          menu_item_id: string;
          quantity: number;
          unit_price_gbp: number;
        };
        Insert: {
          id?: string;
          order_id: string;
          menu_item_id: string;
          quantity: number;
          unit_price_gbp: number;
        };
        Update: never;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_role: UserRole;
      order_status: OrderStatus;
      subscription_tier: SubscriptionTier;
    };
  };
}

// Convenience row types
export type Profile = Database['public']['Tables']['profiles']['Row'];
export type VanOperator = Database['public']['Tables']['van_operators']['Row'];
export type Van = Database['public']['Tables']['vans']['Row'];
export type MenuItem = Database['public']['Tables']['menu_items']['Row'];
export type RouteStop = Database['public']['Tables']['route_stops']['Row'];
export type Order = Database['public']['Tables']['orders']['Row'];
export type OrderItem = Database['public']['Tables']['order_items']['Row'];

// Composite types used across the app
export interface OrderWithItems extends Order {
  order_items: (OrderItem & { menu_items: MenuItem })[];
}

export interface VanWithOperator extends Van {
  van_operators: VanOperator;
}
